services:
  android-container:
    image: budtmo/docker-android:latest
    container_name: android-container
    ports:
      - "6080:6080"
      - "5555:5555"
      - "5554:5554"
    environment:
      EMULATOR_DEVICE: "Samsung Galaxy S10"
      WEB_VNC: "true"
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
    devices:
      - "/dev/kvm:/dev/kvm"
    stdin_open: true
    tty: true
    networks:
      - default

  react-native:
    build: ./app
    container_name: react-native-container
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - android-container
    networks:
      - default
    command: bash -c "npm i && adb connect android-container:5555 && adb wait-for-device && sleep 120 && npx expo login -u $USERNAME -p $PASSWORD && npx expo start --android"
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      env_file: ".env"

networks:
  default:
    driver: bridge